# Generated by Django 4.2.11 on 2024-03-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_author_book_delete_studentcsv_student_delete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
