# Generated by Django 4.2.11 on 2024-03-15 07:15

import django.core.validators
from django.db import migrations, models
import guide.models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0008_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(validators=[guide.models.validate_even])),
            ],
        ),
        migrations.CreateModel(
            name='Things',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator])),
            ],
        ),
    ]
