# Generated by Django 4.2.11 on 2024-03-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0009_stuff_things'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(max_length=50)),
                ('version', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
