# Generated by Django 4.2.11 on 2024-03-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0010_pythonmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pythonmodel',
            options={'verbose_name': 'Python'},
        ),
    ]
