# Generated by Django 4.2.11 on 2024-03-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0011_alter_pythonmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pythonmodel',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Python'},
        ),
    ]
